/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq.tables.records;


import com.devstaff.farm_collector.repositories.jooq.tables.Farmers;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FarmersRecord extends UpdatableRecordImpl<FarmersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.farmers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.farmers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.farmers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.farmers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.farmers.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.farmers.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.farmers.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.farmers.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.farmers.created_on</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.farmers.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.farmers.last_modified_on</code>.
     */
    public void setLastModifiedOn(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.farmers.last_modified_on</code>.
     */
    public OffsetDateTime getLastModifiedOn() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FarmersRecord
     */
    public FarmersRecord() {
        super(Farmers.FARMERS);
    }

    /**
     * Create a detached, initialised FarmersRecord
     */
    public FarmersRecord(Integer id, String name, String createdBy, String lastModifiedBy, OffsetDateTime createdOn, OffsetDateTime lastModifiedOn) {
        super(Farmers.FARMERS);

        setId(id);
        setName(name);
        setCreatedBy(createdBy);
        setLastModifiedBy(lastModifiedBy);
        setCreatedOn(createdOn);
        setLastModifiedOn(lastModifiedOn);
        resetChangedOnNotNull();
    }
}
