/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq.tables.records;


import com.devstaff.farm_collector.repositories.jooq.tables.FarmOperations;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FarmOperationsRecord extends UpdatableRecordImpl<FarmOperationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.farm_operations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.farm_operations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.farm_operations.field_id</code>.
     */
    public void setFieldId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.farm_operations.field_id</code>.
     */
    public Integer getFieldId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.farm_operations.planting_area_size</code>.
     */
    public void setPlantingAreaSize(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.farm_operations.planting_area_size</code>.
     */
    public BigDecimal getPlantingAreaSize() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.farm_operations.amount_expected</code>.
     */
    public void setAmountExpected(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.farm_operations.amount_expected</code>.
     */
    public Integer getAmountExpected() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.farm_operations.amount_harvested</code>.
     */
    public void setAmountHarvested(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.farm_operations.amount_harvested</code>.
     */
    public Integer getAmountHarvested() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.farm_operations.crop_id</code>.
     */
    public void setCropId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.farm_operations.crop_id</code>.
     */
    public Integer getCropId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.farm_operations.year</code>.
     */
    public void setYear(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.farm_operations.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.farm_operations.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.farm_operations.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.farm_operations.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.farm_operations.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.farm_operations.created_on</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.farm_operations.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.farm_operations.last_modified_on</code>.
     */
    public void setLastModifiedOn(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.farm_operations.last_modified_on</code>.
     */
    public OffsetDateTime getLastModifiedOn() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FarmOperationsRecord
     */
    public FarmOperationsRecord() {
        super(FarmOperations.FARM_OPERATIONS);
    }

    /**
     * Create a detached, initialised FarmOperationsRecord
     */
    public FarmOperationsRecord(Integer id, Integer fieldId, BigDecimal plantingAreaSize, Integer amountExpected, Integer amountHarvested, Integer cropId, Integer year, String createdBy, String lastModifiedBy, OffsetDateTime createdOn, OffsetDateTime lastModifiedOn) {
        super(FarmOperations.FARM_OPERATIONS);

        setId(id);
        setFieldId(fieldId);
        setPlantingAreaSize(plantingAreaSize);
        setAmountExpected(amountExpected);
        setAmountHarvested(amountHarvested);
        setCropId(cropId);
        setYear(year);
        setCreatedBy(createdBy);
        setLastModifiedBy(lastModifiedBy);
        setCreatedOn(createdOn);
        setLastModifiedOn(lastModifiedOn);
        resetChangedOnNotNull();
    }
}
