/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq.tables.records;


import com.devstaff.farm_collector.repositories.jooq.tables.Farms;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FarmsRecord extends UpdatableRecordImpl<FarmsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.farms.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.farms.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.farms.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.farms.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.farms.location</code>.
     */
    public void setLocation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.farms.location</code>.
     */
    public String getLocation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.farms.farmer_id</code>.
     */
    public void setFarmerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.farms.farmer_id</code>.
     */
    public Integer getFarmerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.farms.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.farms.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.farms.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.farms.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.farms.created_on</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.farms.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.farms.last_modified_on</code>.
     */
    public void setLastModifiedOn(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.farms.last_modified_on</code>.
     */
    public OffsetDateTime getLastModifiedOn() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FarmsRecord
     */
    public FarmsRecord() {
        super(Farms.FARMS);
    }

    /**
     * Create a detached, initialised FarmsRecord
     */
    public FarmsRecord(Integer id, String name, String location, Integer farmerId, String createdBy, String lastModifiedBy, OffsetDateTime createdOn, OffsetDateTime lastModifiedOn) {
        super(Farms.FARMS);

        setId(id);
        setName(name);
        setLocation(location);
        setFarmerId(farmerId);
        setCreatedBy(createdBy);
        setLastModifiedBy(lastModifiedBy);
        setCreatedOn(createdOn);
        setLastModifiedOn(lastModifiedOn);
        resetChangedOnNotNull();
    }
}
