/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq.tables.records;


import com.devstaff.farm_collector.repositories.jooq.tables.FarmFields;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FarmFieldsRecord extends UpdatableRecordImpl<FarmFieldsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.farm_fields.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.farm_fields.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.farm_fields.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.farm_fields.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.farm_fields.farm_id</code>.
     */
    public void setFarmId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.farm_fields.farm_id</code>.
     */
    public Integer getFarmId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.farm_fields.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.farm_fields.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.farm_fields.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.farm_fields.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.farm_fields.created_on</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.farm_fields.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.farm_fields.last_modified_on</code>.
     */
    public void setLastModifiedOn(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.farm_fields.last_modified_on</code>.
     */
    public OffsetDateTime getLastModifiedOn() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FarmFieldsRecord
     */
    public FarmFieldsRecord() {
        super(FarmFields.FARM_FIELDS);
    }

    /**
     * Create a detached, initialised FarmFieldsRecord
     */
    public FarmFieldsRecord(Integer id, String name, Integer farmId, String createdBy, String lastModifiedBy, OffsetDateTime createdOn, OffsetDateTime lastModifiedOn) {
        super(FarmFields.FARM_FIELDS);

        setId(id);
        setName(name);
        setFarmId(farmId);
        setCreatedBy(createdBy);
        setLastModifiedBy(lastModifiedBy);
        setCreatedOn(createdOn);
        setLastModifiedOn(lastModifiedOn);
        resetChangedOnNotNull();
    }
}
