/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq;


import com.devstaff.farm_collector.repositories.jooq.tables.Crops;
import com.devstaff.farm_collector.repositories.jooq.tables.FarmFields;
import com.devstaff.farm_collector.repositories.jooq.tables.FarmOperations;
import com.devstaff.farm_collector.repositories.jooq.tables.Farmers;
import com.devstaff.farm_collector.repositories.jooq.tables.Farms;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.crops</code>.
     */
    public final Crops CROPS = Crops.CROPS;

    /**
     * The table <code>public.farm_fields</code>.
     */
    public final FarmFields FARM_FIELDS = FarmFields.FARM_FIELDS;

    /**
     * The table <code>public.farm_operations</code>.
     */
    public final FarmOperations FARM_OPERATIONS = FarmOperations.FARM_OPERATIONS;

    /**
     * The table <code>public.farmers</code>.
     */
    public final Farmers FARMERS = Farmers.FARMERS;

    /**
     * The table <code>public.farms</code>.
     */
    public final Farms FARMS = Farms.FARMS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Crops.CROPS,
            FarmFields.FARM_FIELDS,
            FarmOperations.FARM_OPERATIONS,
            Farmers.FARMERS,
            Farms.FARMS
        );
    }
}
