/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq;


import com.devstaff.farm_collector.repositories.jooq.tables.Crops;
import com.devstaff.farm_collector.repositories.jooq.tables.FarmFields;
import com.devstaff.farm_collector.repositories.jooq.tables.FarmOperations;
import com.devstaff.farm_collector.repositories.jooq.tables.Farmers;
import com.devstaff.farm_collector.repositories.jooq.tables.Farms;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.crops</code>.
     */
    public static final Crops CROPS = Crops.CROPS;

    /**
     * The table <code>public.farm_fields</code>.
     */
    public static final FarmFields FARM_FIELDS = FarmFields.FARM_FIELDS;

    /**
     * The table <code>public.farm_operations</code>.
     */
    public static final FarmOperations FARM_OPERATIONS = FarmOperations.FARM_OPERATIONS;

    /**
     * The table <code>public.farmers</code>.
     */
    public static final Farmers FARMERS = Farmers.FARMERS;

    /**
     * The table <code>public.farms</code>.
     */
    public static final Farms FARMS = Farms.FARMS;
}
