/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq.tables;


import com.devstaff.farm_collector.repositories.jooq.Keys;
import com.devstaff.farm_collector.repositories.jooq.Public;
import com.devstaff.farm_collector.repositories.jooq.tables.FarmOperations.FarmOperationsPath;
import com.devstaff.farm_collector.repositories.jooq.tables.Farms.FarmsPath;
import com.devstaff.farm_collector.repositories.jooq.tables.records.FarmFieldsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FarmFields extends TableImpl<FarmFieldsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.farm_fields</code>
     */
    public static final FarmFields FARM_FIELDS = new FarmFields();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FarmFieldsRecord> getRecordType() {
        return FarmFieldsRecord.class;
    }

    /**
     * The column <code>public.farm_fields.id</code>.
     */
    public final TableField<FarmFieldsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.farm_fields.name</code>.
     */
    public final TableField<FarmFieldsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>public.farm_fields.farm_id</code>.
     */
    public final TableField<FarmFieldsRecord, Integer> FARM_ID = createField(DSL.name("farm_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.farm_fields.created_by</code>.
     */
    public final TableField<FarmFieldsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.farm_fields.last_modified_by</code>.
     */
    public final TableField<FarmFieldsRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.farm_fields.created_on</code>.
     */
    public final TableField<FarmFieldsRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.farm_fields.last_modified_on</code>.
     */
    public final TableField<FarmFieldsRecord, OffsetDateTime> LAST_MODIFIED_ON = createField(DSL.name("last_modified_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private FarmFields(Name alias, Table<FarmFieldsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FarmFields(Name alias, Table<FarmFieldsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.farm_fields</code> table reference
     */
    public FarmFields(String alias) {
        this(DSL.name(alias), FARM_FIELDS);
    }

    /**
     * Create an aliased <code>public.farm_fields</code> table reference
     */
    public FarmFields(Name alias) {
        this(alias, FARM_FIELDS);
    }

    /**
     * Create a <code>public.farm_fields</code> table reference
     */
    public FarmFields() {
        this(DSL.name("farm_fields"), null);
    }

    public <O extends Record> FarmFields(Table<O> path, ForeignKey<O, FarmFieldsRecord> childPath, InverseForeignKey<O, FarmFieldsRecord> parentPath) {
        super(path, childPath, parentPath, FARM_FIELDS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FarmFieldsPath extends FarmFields implements Path<FarmFieldsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FarmFieldsPath(Table<O> path, ForeignKey<O, FarmFieldsRecord> childPath, InverseForeignKey<O, FarmFieldsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FarmFieldsPath(Name alias, Table<FarmFieldsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FarmFieldsPath as(String alias) {
            return new FarmFieldsPath(DSL.name(alias), this);
        }

        @Override
        public FarmFieldsPath as(Name alias) {
            return new FarmFieldsPath(alias, this);
        }

        @Override
        public FarmFieldsPath as(Table<?> alias) {
            return new FarmFieldsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FarmFieldsRecord, Integer> getIdentity() {
        return (Identity<FarmFieldsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FarmFieldsRecord> getPrimaryKey() {
        return Keys.FARM_FIELDS_PKEY;
    }

    @Override
    public List<ForeignKey<FarmFieldsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FARM_FIELDS__FK_FARM_FIELDS);
    }

    private transient FarmsPath _farms;

    /**
     * Get the implicit join path to the <code>public.farms</code> table.
     */
    public FarmsPath farms() {
        if (_farms == null)
            _farms = new FarmsPath(this, Keys.FARM_FIELDS__FK_FARM_FIELDS, null);

        return _farms;
    }

    private transient FarmOperationsPath _farmOperations;

    /**
     * Get the implicit to-many join path to the
     * <code>public.farm_operations</code> table
     */
    public FarmOperationsPath farmOperations() {
        if (_farmOperations == null)
            _farmOperations = new FarmOperationsPath(this, null, Keys.FARM_OPERATIONS__FK_FARM_OPERATIONS_FIELDS.getInverseKey());

        return _farmOperations;
    }

    @Override
    public FarmFields as(String alias) {
        return new FarmFields(DSL.name(alias), this);
    }

    @Override
    public FarmFields as(Name alias) {
        return new FarmFields(alias, this);
    }

    @Override
    public FarmFields as(Table<?> alias) {
        return new FarmFields(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmFields rename(String name) {
        return new FarmFields(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmFields rename(Name name) {
        return new FarmFields(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FarmFields rename(Table<?> name) {
        return new FarmFields(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FarmFields where(Condition condition) {
        return new FarmFields(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FarmFields where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FarmFields where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FarmFields where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FarmFields where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FarmFields where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FarmFields where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FarmFields where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FarmFields whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FarmFields whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
