/*
 * This file is generated by jOOQ.
 */
package com.devstaff.farm_collector.repositories.jooq.tables;


import com.devstaff.farm_collector.repositories.jooq.Keys;
import com.devstaff.farm_collector.repositories.jooq.Public;
import com.devstaff.farm_collector.repositories.jooq.tables.FarmFields.FarmFieldsPath;
import com.devstaff.farm_collector.repositories.jooq.tables.Farmers.FarmersPath;
import com.devstaff.farm_collector.repositories.jooq.tables.records.FarmsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Farms extends TableImpl<FarmsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.farms</code>
     */
    public static final Farms FARMS = new Farms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FarmsRecord> getRecordType() {
        return FarmsRecord.class;
    }

    /**
     * The column <code>public.farms.id</code>.
     */
    public final TableField<FarmsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.farms.name</code>.
     */
    public final TableField<FarmsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.farms.location</code>.
     */
    public final TableField<FarmsRecord, String> LOCATION = createField(DSL.name("location"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.farms.farmer_id</code>.
     */
    public final TableField<FarmsRecord, Integer> FARMER_ID = createField(DSL.name("farmer_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.farms.created_by</code>.
     */
    public final TableField<FarmsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.farms.last_modified_by</code>.
     */
    public final TableField<FarmsRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.farms.created_on</code>.
     */
    public final TableField<FarmsRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.farms.last_modified_on</code>.
     */
    public final TableField<FarmsRecord, OffsetDateTime> LAST_MODIFIED_ON = createField(DSL.name("last_modified_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Farms(Name alias, Table<FarmsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Farms(Name alias, Table<FarmsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.farms</code> table reference
     */
    public Farms(String alias) {
        this(DSL.name(alias), FARMS);
    }

    /**
     * Create an aliased <code>public.farms</code> table reference
     */
    public Farms(Name alias) {
        this(alias, FARMS);
    }

    /**
     * Create a <code>public.farms</code> table reference
     */
    public Farms() {
        this(DSL.name("farms"), null);
    }

    public <O extends Record> Farms(Table<O> path, ForeignKey<O, FarmsRecord> childPath, InverseForeignKey<O, FarmsRecord> parentPath) {
        super(path, childPath, parentPath, FARMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class FarmsPath extends Farms implements Path<FarmsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FarmsPath(Table<O> path, ForeignKey<O, FarmsRecord> childPath, InverseForeignKey<O, FarmsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FarmsPath(Name alias, Table<FarmsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FarmsPath as(String alias) {
            return new FarmsPath(DSL.name(alias), this);
        }

        @Override
        public FarmsPath as(Name alias) {
            return new FarmsPath(alias, this);
        }

        @Override
        public FarmsPath as(Table<?> alias) {
            return new FarmsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FarmsRecord, Integer> getIdentity() {
        return (Identity<FarmsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FarmsRecord> getPrimaryKey() {
        return Keys.FARMS_PKEY;
    }

    @Override
    public List<ForeignKey<FarmsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FARMS__FK_FARMERS_FARM);
    }

    private transient FarmersPath _farmers;

    /**
     * Get the implicit join path to the <code>public.farmers</code> table.
     */
    public FarmersPath farmers() {
        if (_farmers == null)
            _farmers = new FarmersPath(this, Keys.FARMS__FK_FARMERS_FARM, null);

        return _farmers;
    }

    private transient FarmFieldsPath _farmFields;

    /**
     * Get the implicit to-many join path to the <code>public.farm_fields</code>
     * table
     */
    public FarmFieldsPath farmFields() {
        if (_farmFields == null)
            _farmFields = new FarmFieldsPath(this, null, Keys.FARM_FIELDS__FK_FARM_FIELDS.getInverseKey());

        return _farmFields;
    }

    @Override
    public Farms as(String alias) {
        return new Farms(DSL.name(alias), this);
    }

    @Override
    public Farms as(Name alias) {
        return new Farms(alias, this);
    }

    @Override
    public Farms as(Table<?> alias) {
        return new Farms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Farms rename(String name) {
        return new Farms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Farms rename(Name name) {
        return new Farms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Farms rename(Table<?> name) {
        return new Farms(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Farms where(Condition condition) {
        return new Farms(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Farms where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Farms where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Farms where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Farms where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Farms where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Farms where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Farms where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Farms whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Farms whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
